

// ------------------------------------------------------------------------------
//  <auto-generated>
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated. 
//  </auto-generated>
// ------------------------------------------------------------------------------

#region Designer generated code
#pragma warning disable

namespace WebAutomationSample.Tests.Pages
{
	using WebAutomation.Core.WebObjects.Common.Attributes;
	using WebAutomation.Core.WebObjects.WebComponents;
	using WebAutomation.Core.WebObjects.WebComponents.Attributes;
	using WebAutomation.Core.WebObjects.WebContainer;
	using WebAutomation.Core.WebObjects.WebContainer.Attributes;

	[Name("QualityExcitesPage")]
	public partial class QualityExcitesPage 
	{
		[Name("ButtonByText")]
		[Pxpath("//button[text()='{0}']")]
		public IWebComponent ButtonByText { get; set; }

		[Name("SubmitButton")]
		[Id("input-submit")]
		public IWebComponent SubmitButton { get; set; }

		[Name("Logo")]
		[Id("logo")]
		public IWebComponent Logo { get; set; }

		[Name("MenuLink")]
		[Pxpath("//li[starts-with(@id, 'menu-item')]/a[text()='{0}']")]
		public IWebComponent MenuLink { get; set; }

		[Name("Header")]
		[Xpath("//h2")]
		public IWebComponent Header { get; set; }

	}

	[Name("CallForProposalsPage")]
	public partial class CallForProposalsPage : QualityExcitesPage
	{
		[Name("Title")]
		[Id("input-temat")]
		public IWebComponent Title { get; set; }

		[Name("Description")]
		[Id("text-abstrakt")]
		public IWebComponent Description { get; set; }

		[Name("Form")]
		[Id("length")]
		public IWebComponent Form { get; set; }

		[Name("Speaker")]
		[Pid("experience_{0}")]
		public IWebComponent Speaker { get; set; }

		[Name("Presented")]
		[Pid("presented_{0}")]
		public IWebComponent Presented { get; set; }

		[Name("Presentation")]
		[Xpath("//a[@id='add-file']/preceding-sibling::div/input[@type='file']")]
		public IWebComponent Presentation { get; set; }

		[Name("FirstName")]
		[Id("input-imie")]
		public IWebComponent FirstName { get; set; }

		[Name("Surname")]
		[Id("input-nazwisko")]
		public IWebComponent Surname { get; set; }

		[Name("Position")]
		[Id("input-stanowisko")]
		public IWebComponent Position { get; set; }

		[Name("CompanyInstitution")]
		[Id("input-firma")]
		public IWebComponent CompanyInstitution { get; set; }

		[Name("EmailAddress")]
		[Id("input-email")]
		public IWebComponent EmailAddress { get; set; }

		[Name("PhoneNumber")]
		[Id("input-phone")]
		public IWebComponent PhoneNumber { get; set; }

		[Name("Biography")]
		[Id("text-biografia")]
		public IWebComponent Biography { get; set; }

		[Name("Photo")]
		[Xpath("//a[@id='add-photo']/preceding-sibling::div/input[@type='file']")]
		public IWebComponent Photo { get; set; }

		[Name("Agreement")]
		[Id("checkbox-regulamin")]
		public IWebComponent Agreement { get; set; }

	}

	[Name("HomePage")]
	public partial class HomePage : QualityExcitesPage
	{
	}

	[Name("ConferencePage")]
	public partial class ConferencePage : QualityExcitesPage
	{
	}

	[Name("QualityMeetupPage")]
	public partial class QualityMeetupPage : QualityExcitesPage
	{
	}

	[Name("OrganisersPage")]
	public partial class OrganisersPage : QualityExcitesPage
	{
	}

	[Name("ContactPage")]
	public partial class ContactPage : QualityExcitesPage
	{
	}

}

#pragma warning restore
#endregion

