

// ------------------------------------------------------------------------------
//  <auto-generated>
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated. 
//  </auto-generated>
// ------------------------------------------------------------------------------

#region Designer generated code
#pragma warning disable

namespace WebAutomationSample.Tests.Pages
{
	using WebAutomation.Core.WebObjects.Common.Attributes;
	using WebAutomation.Core.WebObjects.WebComponents;
	using WebAutomation.Core.WebObjects.WebComponents.Attributes;
	using WebAutomation.Core.WebObjects.WebContainer;
	using WebAutomation.Core.WebObjects.WebContainer.Attributes;

	[Name("QualityExcitesPage")]
	public partial class QualityExcitesPage 
	{
		[Name("Logo")]
		[Id("logo")]
		public IWebComponent Logo { get; set; }

		[Name("MenuLink")]
		[Pxpath("//li[starts-with(@id, 'menu-item')]/a[text()='{0}']")]
		public IWebComponent MenuLink { get; set; }

		[Name("Header")]
		[Xpath("//h2")]
		public IWebComponent Header { get; set; }

	}

	[Name("HomePage")]
	public partial class HomePage : QualityExcitesPage
	{
	}

	[Name("ConferencePage")]
	public partial class ConferencePage : QualityExcitesPage
	{
	}

	[Name("CallForProposalsPage")]
	public partial class CallForProposalsPage : QualityExcitesPage
	{
	}

	[Name("QualityMeetupPage")]
	public partial class QualityMeetupPage : QualityExcitesPage
	{
	}

	[Name("OrganisersPage")]
	public partial class OrganisersPage : QualityExcitesPage
	{
	}

	[Name("ContactPage")]
	public partial class ContactPage : QualityExcitesPage
	{
	}

}

#pragma warning restore
#endregion

