

// ------------------------------------------------------------------------------
//  <auto-generated>
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated. 
//  </auto-generated>
// ------------------------------------------------------------------------------

#region Designer generated code
#pragma warning disable

namespace HowTo.XML.Pages.Approach0
{
	using WebAutomation.Core.WebObjects.Common.Attributes;
	using WebAutomation.Core.WebObjects.WebComponents;
	using WebAutomation.Core.WebObjects.WebComponents.Attributes;
	using WebAutomation.Core.WebObjects.WebContainer;
	using WebAutomation.Core.WebObjects.WebContainer.Attributes;

	[Name("MyWebsite")]
	public partial class MyWebsite 
	{
	}

	[Name("HomePage")]
	public partial class HomePage : MyWebsite
	{
		[Name("MenuHomeButton")]
		[Xpath("//ul[@id='menu']/li/a[text()='Home']")]
		public IWebComponent MenuHomeButton { get; set; }

		[Name("MenuNewsButton")]
		[Xpath("//ul[@id='menu']/li/a[text()='News']")]
		public IWebComponent MenuNewsButton { get; set; }

		[Name("MenuLoginButton")]
		[Xpath("//ul[@id='menu']/li/a[text()='Login']")]
		public IWebComponent MenuLoginButton { get; set; }

	}

	[Name("LoginPage")]
	public partial class LoginPage : MyWebsite
	{
		[Name("MenuHomeButton")]
		[Xpath("//ul[@id='menu']/li/a[text()='Home']")]
		public IWebComponent MenuHomeButton { get; set; }

		[Name("MenuNewsButton")]
		[Xpath("//ul[@id='menu']/li/a[text()='News']")]
		public IWebComponent MenuNewsButton { get; set; }

		[Name("MenuLoginButton")]
		[Xpath("//ul[@id='menu']/li/a[text()='Login']")]
		public IWebComponent MenuLoginButton { get; set; }

		[Name("UserTextbox")]
		[Id("user")]
		public IWebComponent UserTextbox { get; set; }

		[Name("PasswordTextbox")]
		[Id("password")]
		public IWebComponent PasswordTextbox { get; set; }

		[Name("LoginButton")]
		[Id("login")]
		public IWebComponent LoginButton { get; set; }

		[Name("ErrorMessage")]
		[Xpath("//span[@id='message'][text()='Incorrect password!']")]
		public IWebComponent ErrorMessage { get; set; }

		[Name("SuccessMessage")]
		[Xpath("//span[@id='message'][text()='Your are logged!']")]
		public IWebComponent SuccessMessage { get; set; }

	}

	[Name("NewsPage")]
	public partial class NewsPage : MyWebsite
	{
		[Name("MenuHomeButton")]
		[Xpath("//ul[@id='menu']/li/a[text()='Home']")]
		public IWebComponent MenuHomeButton { get; set; }

		[Name("MenuNewsButton")]
		[Xpath("//ul[@id='menu']/li/a[text()='News']")]
		public IWebComponent MenuNewsButton { get; set; }

		[Name("MenuLoginButton")]
		[Xpath("//ul[@id='menu']/li/a[text()='Login']")]
		public IWebComponent MenuLoginButton { get; set; }

		[Name("TableRow1Id")]
		[Xpath("//table/tbody/tr[1]/td[1]")]
		public IWebComponent TableRow1Id { get; set; }

		[Name("TableRow1Title")]
		[Xpath("//table/tbody/tr[1]/td[2]")]
		public IWebComponent TableRow1Title { get; set; }

		[Name("TableRow1Content")]
		[Xpath("//table/tbody/tr[1]/td[3]/div")]
		public IWebComponent TableRow1Content { get; set; }

		[Name("TableRow2Id")]
		[Xpath("//table/tbody/tr[2]/td[1]")]
		public IWebComponent TableRow2Id { get; set; }

		[Name("TableRow2Title")]
		[Xpath("//table/tbody/tr[2]/td[2]")]
		public IWebComponent TableRow2Title { get; set; }

		[Name("TableRow2Content")]
		[Xpath("//table/tbody/tr[2]/td[3]/div")]
		public IWebComponent TableRow2Content { get; set; }

	}

}

#pragma warning restore
#endregion

